targets:
  $default:
    sources:
    - lib/**
    - swagger_examples/**
    - unstable_examples/**
    - $package$
    builders:
      swagger_generator:
        options:
          with_base_url: true
          with_converter: true
          ignore_headers: true
          use_default_null_for_lists: false
          build_only_models: false
          input_folder: 'swagger_examples/'
          output_folder: 'lib/generated_code/'
          default_values_map:
            - type_name: int
              default_value: '36'
          response_override_value_map:
            - url: '/bonuspage/v0/pbo'
              method: get
              overriden_value: 'List<Object>'
            - url: '/bonuspage/v0/personal'
              method: get
              overriden_value: 'List<List<List<List>>>'